export const expectedPluginFiles = [
  ".codex-plugin/plugin.json",
  "ASSET_PROVENANCE.md",
  "LICENSE",
  "adapters/claude/SKILL.md",
  "adapters/deepseek/SKILL.md",
  "adapters/gemini/SKILL.md",
  "adapters/generic/AGENT.md",
  "assets/visual-grounding/canonical-protagonist.png",
  "assets/visual-grounding/manifest.json",
  "assets/visual-grounding/processing-action-hands.png",
  "assets/visual-grounding/processing-with-bubble.png",
  "assets/visual-grounding/processing-without-bubble.png",
  "config/execution-modes.json",
  "protocol/execution-modes.schema.json",
  "protocol/mouse-ui-project.schema.json",
  "protocol/workflow-brief.schema.json",
  "references/qa.md",
  "references/style-independence.md",
  "references/visual-grounding.md",
  "references/workflow-to-ui.md",
  "scripts/resolve-mode.mjs",
  "scripts/validate-workflow.mjs",
  "scripts/verify-bundle.mjs",
  "skills/fantasy-mouse-ui/SKILL.md",
] as const;
